# Generated by Django 4.2.14 on 2024-11-05 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import receipt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_paymentoption_options'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(blank=True, default='False', null=True)),
                ('receipt_doc', models.FileField(blank=True, default='default.pdf', max_length=500, null=True, upload_to='receipt_docs')),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('note', models.CharField(blank=True, max_length=240, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('taxable', models.BooleanField(blank=True, default=True, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_receipt', to='documents.client')),
                ('payment_account', models.ForeignKey(default=receipt.models.get_default_payment_option_account, on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentoption')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('item_description', models.CharField(max_length=800)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.receipt')),
            ],
        ),
    ]
