# Generated by Django 4.2.14 on 2024-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_status',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
