# Generated by Django 4.2.14 on 2025-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_receipt_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Final')], default=0),
        ),
    ]
