# Generated by Django 4.2.14 on 2024-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(default='steve', upload_to='business_logos/'),
            preserve_default=False,
        ),
    ]
