# Generated by Django 4.2.14 on 2024-10-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentoption',
            options={'verbose_name': 'Payment Options'},
        ),
    ]
