# Generated by Django 4.2.14 on 2024-09-06 15:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='theme_color',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[accounts.models.validate_image_size]),
        ),
    ]
