# Generated by Django 4.2.14 on 2024-09-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessaccount_alternative_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaccount',
            old_name='alternative_phone_number',
            new_name='tel',
        ),
    ]
