# Generated by Django 4.2.14 on 2024-09-06 18:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_alternative_phone_number_businessaccount_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to, validators=[accounts.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='theme_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
