# Generated by Django 4.2.14 on 2024-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, default='business_logos/AS_LOGO.png', null=True, upload_to='business_logos/'),
        ),
    ]
