# Generated by Django 4.2.14 on 2024-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_businessaccount_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos'),
        ),
    ]
