# Generated by Django 4.2.14 on 2024-09-06 19:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessaccount_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/', validators=[accounts.models.validate_image_size]),
        ),
    ]
