# Generated by Django 4.2.14 on 2024-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_businessaccount_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='logo',
            field=models.ImageField(blank=True, default='AS_LOGO.png', null=True, upload_to='business_logos/'),
        ),
    ]
