# Generated by Django 4.2.11 on 2024-04-20 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.BooleanField(blank=True, default='False', null=True)),
                ('quotation_doc', models.FileField(default='default.jpg', upload_to='quotation')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.client')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.quotation')),
            ],
        ),
    ]
