# Generated by Django 4.2.11 on 2024-04-27 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_doc',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='quotation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
