# Generated by Django 4.2.14 on 2024-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Final')], default=0),
        ),
    ]
