# Generated by Django 4.2.14 on 2024-08-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds'), ('g', 'Grams'), ('oz', 'Ounces')], max_length=2, null=True),
        ),
    ]
