# Generated by Django 4.2.13 on 2024-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_quotation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='name',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='quotation',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
