# Generated by Django 4.2.14 on 2024-09-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_client_business_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='user',
        ),
    ]
