# Generated by Django 4.2.14 on 2025-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitems',
            name='item_image',
            field=models.ImageField(blank=True, default='item_images/AS_LOGO.png', null=True, upload_to='item_images/'),
        ),
    ]
