# Generated by Django 4.2.13 on 2024-05-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_name_quotation_data_remove_quotation_qr_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
