# Generated by Django 4.2.13 on 2024-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_taxable_quotation_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='note',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
