# Generated by Django 4.2.14 on 2024-10-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='taxable',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitems',
            name='price',
        ),
    ]
