# Generated by Django 4.2.14 on 2024-09-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='business_account',
        ),
    ]
