# Generated by Django 4.2.14 on 2024-11-16 10:24

import deliverynote.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paymentoption_options'),
        ('deliverynote', '0002_remove_deliverynote_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='note',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='payment_account',
            field=models.ForeignKey(default=deliverynote.models.get_default_payment_option_account, on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentoption'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='payment_status',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
