# Generated by Django 4.2.14 on 2024-10-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynote', '0002_alter_deliverynote_sub_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='note',
        ),
    ]
