# Generated by Django 4.2.14 on 2024-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynote', '0003_deliverynote_note_deliverynote_payment_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Final')], default=0),
        ),
    ]
