# Generated by Django 4.2.14 on 2024-11-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynote', '0004_alter_deliverynote_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='note',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
