# Generated by Django 4.2.14 on 2025-02-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynote', '0005_alter_deliverynote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteitems',
            name='item_image',
            field=models.ImageField(blank=True, default='item_images/AS_LOGO.png', null=True, upload_to='item_images/'),
        ),
    ]
