# Generated by Django 4.2.14 on 2024-10-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentOption',
        ),
    ]
