# Generated by Django 4.2.14 on 2024-08-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
