# Generated by Django 4.2.14 on 2024-08-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_option',
        ),
    ]
