# Generated by Django 4.2.14 on 2024-08-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_account_address_alter_account_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
