# Generated by Django 4.2.14 on 2024-09-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_invoiceitems_unit'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='BusinessAccount',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Business_account', to='documents.client'),
            preserve_default=False,
        ),
    ]
