# Generated by Django 4.2.14 on 2024-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='business_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
