# Generated by Django 4.2.14 on 2024-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
