# Generated by Django 4.2.14 on 2024-09-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_businessaccount_logo'),
        ('invoice', '0002_invoice_businessaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='BusinessAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Business_account', to='accounts.businessaccount'),
        ),
    ]
