# Generated by Django 4.2.14 on 2025-02-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='item_image',
            field=models.ImageField(blank=True, default='item_images/AS_LOGO.png', null=True, upload_to='item_images/'),
        ),
    ]
